# See config options and defaults:
#   https://docs.astral.sh/ruff/settings/
# ##############################################################################
#
# Style guides in order of precedence (1 overrides 2, 2 overrides 3, ...)
# 1. Team style guide:
#    - https://dev.azure.com/SHI-DataScience/Data%20Science/_wiki/wikis/Data-Science.wiki/534/Style-Guide
# 2. Google style guide:
#    - https://google.github.io/styleguide/pyguide.html
# 3. PEP8
#    - https://peps.python.org/pep-0008/
# 4. Use your best judgement.
# ##############################################################################


# Per the AI/ML team style guide.
line-length = 120


[format]
# Like Black, use double quotes for strings.
quote-style = "double"


# Like Black, indent with spaces, rather than tabs.
indent-style = "space"


# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false


# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"


# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true


[lint]
# ANN - Issues raised by flake8-annotations
# B - Issues raised by flake8-bugbear, includes the B9xx which are more opinionated
# BLK - Issues raised by Black
# C - Issues rasied by mccabe (complexity)
# D - Issues raised by pydocstyle
# E - Errors reported by pycodestyle
# DAR - Issues raised by darglint
# F - Errors raised by pyflakes
# I - Issues raised by flake8-import-order
# S - Issues raised by flake8-bandit (security)
# W - Warnings reported by pycodestyle
# ---
# !!!: I was looking at the `pyproject.toml` for pendulum and saw some things that interested me.
# 1. Review https://docs.astral.sh/ruff/rules/ for groups that are not yet included.
# 1. Experiment if needed.
# 1. Add to the list below.
# 1. Process the old + new list.
# 1. Output this structure:
#    - In alphabetical order, comment with description for the group.
#    - In alphabetical order, the `select = [...]` line.
# ???: See if there is a way that you can eaisily test each of these groups to see how they might
#      impact existing code.
# ???: Would it be better to invert the selection?  Can I do a `select ['*']` and then `ignore = [...]`?
# ???: Currently, I use `C` for complexity, but the docs now say `C90`.  Should I change that?  See `T10` below too.
# ???: Conflicts?  Will all of these play well together?
# !!!: See the `ruff.toml` file in the [faststream](https://github.com/ag2ai/faststream/blob/main/ruff.toml) repo for a reference on how someone else has done this.
# ---
# FAST - Issues raised by FastAPI linter
# ASYNC - Issues raised by flake8-async
# BLE - Issues raised by flake8-blind-except
# FBT - Issues raised by flake8-boolean-trap
# A - Issues raised by flake8-builtins
# COM - Issues raised by flake8-commas
# C4 - Issues raised by flake8-comprehensions
# DTZ - Issues raised by flake8-datetimez
# T10 - Issues raised by flake8-debugger
# EM - Issues raised by flake8-errormsg
# EXE - Issues raised by flake8-executable
# ISC - Issues raised by flake8-implicit-str-concat
# LOG - Issues raised by flake8-logging
# G - Issues raised by flake8-logging-format
# ?PIE - Issues raised by flake8-pie
# T20 - Issues raised by flake8-print
# RSE - Issues raised by flake8-raise
# ?RET - Issues raised by flake8-return
# ?PT - Issues raised by flake8-pytest-style
# ?SLF - Issues raised by flake8-self
# SIM - Issues raised by flake8-simplify
# SLOT - Issues raised by flake8-slots
# ?TD - Issues raised by flake8-todos
# ?TC - Issues rasied by flake8-type-checking
# PTH - Issues raised by flake8-use-pathlib
# NPY - Numpy specific rules
# PD - Issues raised by pandas-vet
# ?N - Issues raised by pip8-naming
# PERF - Issues raised by perflint
# ?DOC - Issues raised by pydoclint
# ?PLC - Issues rased by pylint (convention)
# ?PLE - Issues rased by pylint (error)
# ?PLR - Issues rased by pylint (refactor)
# ?PLW - Issues rased by pylint (warning)
# UP - Issues raised by pyupgrade
# FURB - Issues raised by refurb
# RUF - Ruff specific rules
# ?TRY - Issues raised by tryceratops
select = ["ANN", "B", "B9", "C", "D", "E", "F", "I", "S", "W"]


# https://docs.astral.sh/ruff/rules/
#
# D105 - Missing docstring in magic (e.g., `__str__`, `__repr__`, etc.) method.
# D107 - Missing docstring in `__init__` method.
# E203 - Whitespace before ':'
# E501 - Line too long; With B9 enabled this is a duplicate of B950.  Disable it to avoid duplicate.
#        Unlike E501, from pycodestyle, B950 only triggers if max-line-length is exceeded by 10% or
#        more.  Inspired by Raymond Hettinger's "Beyond PEP8" talk.
ignore = ["D105", "D107", "E203", "E501"]


# Require that a human fix these classes of errors.
unfixable = ["B"]


[lint.per-file-ignores]
# D104 - Missing docstring in public package.
# S101 - Use of assert keyword.
"__init__.py" = ["D104"]
"tests/*" = ["D"]
"integration-tests/*" = ["S101"]


[lint.isort]
section-order = [
    "future",
    "standard-library",
    "langchain",
    "third-party",
    "first-party",
    "local-folder",
    "testing",
    "first-party-testsuite",
]


[lint.isort.sections]
"testing" = ["unittest", "pytest", "hypothesis", "testcontainers", "behave"]
"langchain" = ["langchain-*"]
"first-party-testsuite" = ["tests"]


[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds this value.
max-complexity = 7


[lint.pep8-naming]
classmethod-decorators = [
    # Allow Pydantic's `@validator` decorator to trigger class method treatment.
    "pydantic.validator",
    # Allow SQLAlchemy's dynamic decorators, like `@field.expression`, to trigger class method treatment.
    "declared_attr",
    "expression",
    "comparator",
]


[lint.pycodestyle]
# Ignore line-length violations (E501) for comments starting with
# `task-tags` (By default: `TODO`, `FIXME`, and `XXX`).
ignore-overlong-task-comments = true


[lint.pydocstyle]
convention = "google"
