
# Source the bashrc file if it exists

    [ -f $HOME/.local/etc/bashrc ] && source $HOME/.local/bashrc


# Load all of the files from the login.d directory

    if [ -d $HOME/.local/etc/login.d ]; then
        for file in $HOME/.local/etc/login.d/*.sh; do
            source $file
        done
    fi
